# Generated by Django 4.2.29 on 2026-03-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.FloatField()),
                ('unit', models.CharField(default='', max_length=30)),
                ('source', models.CharField(default='system', max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OperationalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('csv', 'CSV Upload'), ('iot', 'IoT Sensor'), ('server', 'Server Log'), ('network', 'Network Monitor')], max_length=20)),
                ('source_name', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('memory_usage', models.FloatField(blank=True, null=True)),
                ('disk_io', models.FloatField(blank=True, null=True)),
                ('network_throughput', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('error_rate', models.FloatField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('is_validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'operational_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='operational_timesta_e5d908_idx'), models.Index(fields=['source_type'], name='operational_source__e3facc_idx'), models.Index(fields=['is_validated'], name='operational_is_vali_a657e0_idx')],
            },
        ),
    ]
