# Generated by Django 4.2.29 on 2026-03-13 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('isolation_forest', 'Isolation Forest'), ('zscore', 'Z-Score'), ('combined', 'Combined')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('anomaly_score', models.FloatField(help_text='Score from the detection algorithm')),
                ('affected_fields', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('data_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='ingestion.operationaldata')),
            ],
            options={
                'db_table': 'anomaly_records',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['severity'], name='anomaly_rec_severit_cd0714_idx'), models.Index(fields=['algorithm'], name='anomaly_rec_algorit_46751f_idx')],
            },
        ),
    ]
