# Generated by Django 4.2.29 on 2026-03-13 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliabilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(blank=True, default='', max_length=100)),
                ('completeness_score', models.FloatField(help_text='% of non-null fields (0-100)')),
                ('consistency_score', models.FloatField(help_text='Score based on value range validation (0-100)')),
                ('uniqueness_score', models.FloatField(help_text='Score penalizing duplicates (0-100)')),
                ('overall_score', models.FloatField(help_text='Weighted average reliability score (0-100)')),
                ('issues_found', models.JSONField(blank=True, default=list)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('data_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reliability_score', to='ingestion.operationaldata')),
            ],
            options={
                'db_table': 'reliability_scores',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
